/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        adminClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        adminOptions = new javax.swing.JTabbedPane();
        allocateCourse = new javax.swing.JPanel();
        allocInput = new javax.swing.JTextField();
        allocLabel = new javax.swing.JLabel();
        courseIdLabel = new javax.swing.JLabel();
        serialLabel = new javax.swing.JLabel();
        allocButton = new javax.swing.JButton();
        courseInput = new java.awt.Choice();
        serialInput = new java.awt.Choice();
        lecturerPanel = new javax.swing.JPanel();
        passwdInput = new javax.swing.JTextField();
        lecNameInput = new javax.swing.JTextField();
        lecSerialInput = new javax.swing.JTextField();
        lecProgramChoice = new java.awt.Choice();
        lecSerialLabel = new javax.swing.JLabel();
        lecNameLabel = new javax.swing.JLabel();
        lecEmailLabel = new javax.swing.JLabel();
        programLabel = new javax.swing.JLabel();
        addLecturer = new javax.swing.JButton();
        passwdLabel = new javax.swing.JLabel();
        lecEmailInput1 = new javax.swing.JTextField();
        addStudent = new javax.swing.JPanel();
        regNo = new javax.swing.JTextField();
        studentName = new javax.swing.JTextField();
        studentPasswdInput = new javax.swing.JTextField();
        regLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        addStButton = new javax.swing.JButton();
        studentEmail1 = new javax.swing.JTextField();
        stPasswdLabel = new javax.swing.JLabel();
        programPanel = new javax.swing.JPanel();
        pDurationInput = new javax.swing.JTextField();
        pNameInput = new javax.swing.JTextField();
        pIdInput = new javax.swing.JTextField();
        pIdLabel = new javax.swing.JLabel();
        pNameLabel = new javax.swing.JLabel();
        pDurationLabel = new javax.swing.JLabel();
        addProgramButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(223, 49, 80));

        adminClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/close.png"))); // NOI18N
        adminClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminCloseMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/adminPage.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN DASHBOARD");

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/refresh25.png"))); // NOI18N
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                refreshMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminClose)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminClose)
                    .addComponent(refresh))
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        allocateCourse.setAutoscrolls(true);

        allocLabel.setText("Allocation ID");

        courseIdLabel.setText("course ID");

        serialLabel.setText("Serial No");

        allocButton.setBackground(new java.awt.Color(223, 49, 80));
        allocButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allocButton.setForeground(new java.awt.Color(255, 255, 255));
        allocButton.setText("Allocate course");
        allocButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                allocButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout allocateCourseLayout = new javax.swing.GroupLayout(allocateCourse);
        allocateCourse.setLayout(allocateCourseLayout);
        allocateCourseLayout.setHorizontalGroup(
            allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allocateCourseLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, allocateCourseLayout.createSequentialGroup()
                            .addComponent(allocLabel)
                            .addGap(72, 72, 72)
                            .addComponent(allocInput, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(allocateCourseLayout.createSequentialGroup()
                            .addGroup(allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(serialLabel)
                                .addComponent(courseIdLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(courseInput, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(serialInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(allocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(255, 255, 255))
        );
        allocateCourseLayout.setVerticalGroup(
            allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allocateCourseLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(allocInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allocLabel))
                .addGap(32, 32, 32)
                .addGroup(allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(courseIdLabel)
                    .addComponent(courseInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(allocateCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serialLabel)
                    .addComponent(serialInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(allocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        adminOptions.addTab("tab2", allocateCourse);

        lecturerPanel.setAutoscrolls(true);

        lecSerialLabel.setText("Serial No");

        lecNameLabel.setText("Name");

        lecEmailLabel.setText("Email");

        programLabel.setText("program ID");

        addLecturer.setBackground(new java.awt.Color(223, 49, 80));
        addLecturer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addLecturer.setForeground(new java.awt.Color(255, 255, 255));
        addLecturer.setText("Add lecturer");
        addLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addLecturerMousePressed(evt);
            }
        });

        passwdLabel.setText("Password");

        javax.swing.GroupLayout lecturerPanelLayout = new javax.swing.GroupLayout(lecturerPanel);
        lecturerPanel.setLayout(lecturerPanelLayout);
        lecturerPanelLayout.setHorizontalGroup(
            lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lecSerialLabel)
                    .addComponent(lecNameLabel)
                    .addComponent(lecEmailLabel)
                    .addComponent(programLabel)
                    .addComponent(passwdLabel))
                .addGap(69, 69, 69)
                .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecProgramChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lecSerialInput, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                        .addComponent(lecNameInput))
                    .addComponent(lecEmailInput1))
                .addGap(59, 59, 59)
                .addComponent(addLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        lecturerPanelLayout.setVerticalGroup(
            lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lecturerPanelLayout.createSequentialGroup()
                        .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lecturerPanelLayout.createSequentialGroup()
                                .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(lecturerPanelLayout.createSequentialGroup()
                                        .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lecSerialInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(addLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lecSerialLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lecNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lecNameLabel))
                                .addGap(18, 18, 18)
                                .addComponent(lecEmailInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lecEmailLabel))
                        .addGap(18, 18, 18)
                        .addGroup(lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwdLabel))
                        .addGap(45, 45, 45)
                        .addComponent(programLabel))
                    .addComponent(lecProgramChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        adminOptions.addTab("tab3", lecturerPanel);

        addStudent.setAutoscrolls(true);
        addStudent.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addStudentComponentShown(evt);
            }
        });

        regNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNoActionPerformed(evt);
            }
        });

        regLabel.setText("Registration No");

        nameLabel.setText("Name");

        idLabel.setText("Program ID");

        emailLabel.setText("Email");

        addStButton.setBackground(new java.awt.Color(223, 49, 80));
        addStButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addStButton.setForeground(new java.awt.Color(255, 255, 255));
        addStButton.setText("Add student");
        addStButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addStButtonMousePressed(evt);
            }
        });

        stPasswdLabel.setText("Password");

        javax.swing.GroupLayout addStudentLayout = new javax.swing.GroupLayout(addStudent);
        addStudent.setLayout(addStudentLayout);
        addStudentLayout.setHorizontalGroup(
            addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudentLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(regLabel)
                    .addComponent(emailLabel)
                    .addComponent(nameLabel)
                    .addComponent(stPasswdLabel))
                .addGap(48, 48, 48)
                .addGroup(addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentPasswdInput, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(studentName, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(regNo)
                    .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(addStButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        addStudentLayout.setVerticalGroup(
            addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addStudentLayout.createSequentialGroup()
                        .addGroup(addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regLabel)
                            .addComponent(addStButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameLabel))
                .addGap(29, 29, 29)
                .addGroup(addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(studentEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentPasswdInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stPasswdLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStudentLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(idLabel)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addStudentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        adminOptions.addTab("tab1", addStudent);

        programPanel.setAutoscrolls(true);

        pIdLabel.setText("Program ID");

        pNameLabel.setText("Program Name");

        pDurationLabel.setText("Duration");

        addProgramButton.setBackground(new java.awt.Color(223, 49, 80));
        addProgramButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addProgramButton.setForeground(new java.awt.Color(255, 255, 255));
        addProgramButton.setText("Add program");
        addProgramButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addProgramButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout programPanelLayout = new javax.swing.GroupLayout(programPanel);
        programPanel.setLayout(programPanelLayout);
        programPanelLayout.setHorizontalGroup(
            programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProgramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(programPanelLayout.createSequentialGroup()
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pIdLabel)
                            .addComponent(pDurationLabel)
                            .addComponent(pNameLabel))
                        .addGap(50, 50, 50)
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pDurationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        programPanelLayout.setVerticalGroup(
            programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pIdInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pIdLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pNameLabel)
                    .addComponent(pNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pDurationInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pDurationLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39)
                .addComponent(addProgramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        adminOptions.addTab("tab4", programPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminOptions)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminOptions)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNoActionPerformed

    private void addStudentComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addStudentComponentShown
        // TODO add your handling code here:
        try{
            Conn newConnection = new Conn();
            String query1 = "SELECT * FROM programmes";
            ResultSet rs4 = newConnection.s.executeQuery(query1);
            
            this.choice1.removeAll();
            while(rs4.next()){
                this.choice1.add(rs4.getString("programID"));
                
            }
            rs4.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        
        
        
        
    }//GEN-LAST:event_addStudentComponentShown

    private void adminCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminCloseMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new SplashScreen().show();
    }//GEN-LAST:event_adminCloseMousePressed

    private void addStButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStButtonMousePressed
        // TODO add your handling code here:
        try{
            Conn newConnection = new Conn();
            String addScore = "INSERT INTO student VALUES("+"'"+this.regNo.getText()+"'"+","+"'"+this.studentName.getText()+"'"+","+"'"+this.studentEmail1.getText()+"'"+","+"'"+this.choice1.getSelectedItem()+"'"+","+"'"+this.studentPasswdInput.getText()+"'"+")" ;
            newConnection.s.executeUpdate(addScore);
            JOptionPane.showMessageDialog(this, this.studentName.getText()+"added successfully");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_addStButtonMousePressed

    private void allocButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allocButtonMousePressed
        // TODO add your handling code here:
        try{
            Conn newConnection = new Conn();
            String addCourse = "INSERT INTO leccourseallocation VALUES("+"'"+this.allocInput.getText()+"'"+","+"'"+this.courseInput.getSelectedItem()+"'"+","+"'"+this.serialInput.getSelectedItem()+"'"+")" ;
            newConnection.s.executeUpdate(addCourse);
            JOptionPane.showMessageDialog(this, this.courseInput.getSelectedItem()+"added successfully");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_allocButtonMousePressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Random random = new Random();
        this.allocInput.setText("'"+random.nextInt(10000)+"'");
        addCourseOptions();
        addSerialOptions();
        addProgramOptions();
    }//GEN-LAST:event_formComponentShown

    private void addLecturerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLecturerMousePressed
        // TODO add your handling code here:
        try{
            Conn newConnection = new Conn();
            String addLecturer = "INSERT INTO lecturer VALUES("+"'"+this.lecSerialInput.getText()+"'"+","+"'"+this.lecNameInput.getText()+"'"+","+"'"+this.lecEmailInput1.getText()+"'"+","+"'"+this.lecProgramChoice.getSelectedItem()+"'"+","+"'"+this.passwdInput.getText()+"'"+")" ;
            newConnection.s.executeUpdate(addLecturer);
            JOptionPane.showMessageDialog(this, this.lecSerialInput.getText()+"added successfully");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_addLecturerMousePressed

    private void addProgramButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProgramButtonMousePressed
        // TODO add your handling code here:
        try{
            Conn newConnection = new Conn();
            String addProgram = "INSERT INTO programmes VALUES("+"'"+this.pIdInput.getText()+"'"+","+"'"+this.pNameInput.getText()+"'"+","+"'"+this.pDurationInput.getText()+"'"+")" ;
            newConnection.s.executeUpdate(addProgram);
            JOptionPane.showMessageDialog(this, this.pIdInput.getText()+"added successfully");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_addProgramButtonMousePressed

    private void refreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMousePressed
        // TODO add your handling code here:
        this.courseInput.removeAll();
        this.serialInput.removeAll();
        this.lecProgramChoice.removeAll();
        
        addCourseOptions();
        addSerialOptions();
        addProgramOptions();
    }//GEN-LAST:event_refreshMousePressed
    public void addCourseOptions(){
        try{
            Conn newConnection = new Conn();
            String query1 = "SELECT * FROM courses";
            ResultSet rs4 = newConnection.s.executeQuery(query1);
            
            while(rs4.next()){
                this.courseInput.add(rs4.getString("courseID"));
                
            }
            rs4.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    public void addSerialOptions(){
        try{
            Conn newConnection = new Conn();
            String query1 = "SELECT * FROM lecturer";
            ResultSet rs4 = newConnection.s.executeQuery(query1);
            
            while(rs4.next()){
                this.serialInput.add(rs4.getString("serialNo"));
                
            }
            rs4.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    public void addProgramOptions(){
        try{
            Conn newConnection = new Conn();
            String query1 = "SELECT * FROM programmes";
            ResultSet rs4 = newConnection.s.executeQuery(query1);
            
            while(rs4.next()){
                this.lecProgramChoice.add(rs4.getString("programID"));
                
            }
            rs4.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLecturer;
    private javax.swing.JButton addProgramButton;
    private javax.swing.JButton addStButton;
    private javax.swing.JPanel addStudent;
    private javax.swing.JLabel adminClose;
    private javax.swing.JTabbedPane adminOptions;
    private javax.swing.JButton allocButton;
    private javax.swing.JTextField allocInput;
    private javax.swing.JLabel allocLabel;
    private javax.swing.JPanel allocateCourse;
    private java.awt.Choice choice1;
    private javax.swing.JLabel courseIdLabel;
    private java.awt.Choice courseInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lecEmailInput1;
    private javax.swing.JLabel lecEmailLabel;
    private javax.swing.JTextField lecNameInput;
    private javax.swing.JLabel lecNameLabel;
    private java.awt.Choice lecProgramChoice;
    private javax.swing.JTextField lecSerialInput;
    private javax.swing.JLabel lecSerialLabel;
    private javax.swing.JPanel lecturerPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField pDurationInput;
    private javax.swing.JLabel pDurationLabel;
    private javax.swing.JTextField pIdInput;
    private javax.swing.JLabel pIdLabel;
    private javax.swing.JTextField pNameInput;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JTextField passwdInput;
    private javax.swing.JLabel passwdLabel;
    private javax.swing.JLabel programLabel;
    private javax.swing.JPanel programPanel;
    private javax.swing.JLabel refresh;
    private javax.swing.JLabel regLabel;
    private javax.swing.JTextField regNo;
    private java.awt.Choice serialInput;
    private javax.swing.JLabel serialLabel;
    private javax.swing.JLabel stPasswdLabel;
    private javax.swing.JTextField studentEmail1;
    private javax.swing.JTextField studentName;
    private javax.swing.JTextField studentPasswdInput;
    // End of variables declaration//GEN-END:variables
}
