/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 * MEMBERS
 * EB1/56386/21 - Nimrod Nyongesa
 * EB1/52821/21 - Isaac Mbugua
 * EB1/56429/21 - Nimrod Kibet
 * EB1/56042/21 - Austin Njoroge
 * EB1/56386/21 - Victor Preston
*/
package main;
import javax.swing.JPanel;
import java.util.*;
import java.nio.charset.StandardCharsets;
import java.text.ParseException;
import java.io.*;

/**
 *
 * @author Administrator
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        systemTitle = new javax.swing.JLabel();
        systemType = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchInput = new javax.swing.JTextArea();
        searchBottomBorder = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        homeOption = new javax.swing.JPanel();
        homeTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentOption = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lecturersOption = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        loginOption = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        adminOption = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aboutOption = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        background.setBackground(new java.awt.Color(255, 255, 255));

        titleBar.setBackground(new java.awt.Color(223, 49, 80));
        titleBar.setForeground(new java.awt.Color(255, 255, 255));
        titleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        systemTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        systemTitle.setForeground(new java.awt.Color(255, 255, 255));
        systemTitle.setText("Waanzilishi");
        titleBar.add(systemTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 180, -1));

        systemType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        systemType.setForeground(new java.awt.Color(255, 255, 255));
        systemType.setText("School Management System");
        titleBar.add(systemType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 290, -1));

        jScrollPane1.setBackground(new java.awt.Color(45, 118, 232));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        searchInput.setBackground(new java.awt.Color(223, 49, 80));
        searchInput.setColumns(20);
        searchInput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchInput.setForeground(new java.awt.Color(255, 255, 255));
        searchInput.setRows(5);
        searchInput.setBorder(null);
        searchInput.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(searchInput);

        titleBar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 360, 20));
        titleBar.add(searchBottomBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 380, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/search.png"))); // NOI18N
        titleBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/close.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        titleBar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/telegram.png"))); // NOI18N
        titleBar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -10, 80, 110));

        homeOption.setBackground(java.awt.SystemColor.controlHighlight);
        homeOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeOptionMouseExited(evt);
            }
        });

        homeTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeTitle.setForeground(new java.awt.Color(223, 49, 80));
        homeTitle.setText("Home");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/home.png"))); // NOI18N

        javax.swing.GroupLayout homeOptionLayout = new javax.swing.GroupLayout(homeOption);
        homeOption.setLayout(homeOptionLayout);
        homeOptionLayout.setHorizontalGroup(
            homeOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeOptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homeOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(homeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        homeOptionLayout.setVerticalGroup(
            homeOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeOptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(homeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        studentOption.setBackground(java.awt.SystemColor.controlHighlight);
        studentOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentOptionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentOptionMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(223, 49, 80));
        jLabel4.setText("Student");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/students2.png"))); // NOI18N

        javax.swing.GroupLayout studentOptionLayout = new javax.swing.GroupLayout(studentOption);
        studentOption.setLayout(studentOptionLayout);
        studentOptionLayout.setHorizontalGroup(
            studentOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentOptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(studentOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentOptionLayout.setVerticalGroup(
            studentOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentOptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        lecturersOption.setBackground(java.awt.SystemColor.controlHighlight);
        lecturersOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lecturersOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lecturersOptionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lecturersOptionMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(223, 49, 80));
        jLabel5.setText("Lecturer");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/lecturers.png"))); // NOI18N

        javax.swing.GroupLayout lecturersOptionLayout = new javax.swing.GroupLayout(lecturersOption);
        lecturersOption.setLayout(lecturersOptionLayout);
        lecturersOptionLayout.setHorizontalGroup(
            lecturersOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturersOptionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(lecturersOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lecturersOptionLayout.setVerticalGroup(
            lecturersOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lecturersOptionLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(29, 29, 29))
        );

        loginOption.setBackground(java.awt.SystemColor.controlHighlight);
        loginOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginOptionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginOptionMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(223, 49, 80));
        jLabel11.setText("Login");
        jLabel11.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel11ComponentShown(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/login2.png"))); // NOI18N

        javax.swing.GroupLayout loginOptionLayout = new javax.swing.GroupLayout(loginOption);
        loginOption.setLayout(loginOptionLayout);
        loginOptionLayout.setHorizontalGroup(
            loginOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginOptionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(loginOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        loginOptionLayout.setVerticalGroup(
            loginOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginOptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(26, 26, 26))
        );

        adminOption.setBackground(java.awt.SystemColor.controlHighlight);
        adminOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminOptionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminOptionMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(223, 49, 80));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(223, 49, 80));
        jLabel6.setText("Admin");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/admin.png"))); // NOI18N

        javax.swing.GroupLayout adminOptionLayout = new javax.swing.GroupLayout(adminOption);
        adminOption.setLayout(adminOptionLayout);
        adminOptionLayout.setHorizontalGroup(
            adminOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminOptionLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(adminOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20))
        );
        adminOptionLayout.setVerticalGroup(
            adminOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminOptionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );

        aboutOption.setBackground(java.awt.SystemColor.controlHighlight);
        aboutOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutOptionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutOptionMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(223, 49, 80));
        jLabel7.setText("About");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/about.png"))); // NOI18N

        javax.swing.GroupLayout aboutOptionLayout = new javax.swing.GroupLayout(aboutOption);
        aboutOption.setLayout(aboutOptionLayout);
        aboutOptionLayout.setHorizontalGroup(
            aboutOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutOptionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(aboutOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        aboutOptionLayout.setVerticalGroup(
            aboutOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutOptionLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(24, 24, 24))
        );

        userId.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        userId.setForeground(new java.awt.Color(223, 49, 80));
        userId.setText("User >>");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homeOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lecturersOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aboutOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userId, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lecturersOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MousePressed

    private void homeOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeOptionMouseEntered
        // TODO add your handling code here:
        setColor(homeOption);
    }//GEN-LAST:event_homeOptionMouseEntered

    private void homeOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeOptionMouseExited
        // TODO add your handling code here:
        resetColor(homeOption);
    }//GEN-LAST:event_homeOptionMouseExited

    private void studentOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentOptionMouseEntered
        // TODO add your handling code here:
        setColor(studentOption);
    }//GEN-LAST:event_studentOptionMouseEntered

    private void studentOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentOptionMouseExited
        // TODO add your handling code here:
        resetColor(studentOption);
    }//GEN-LAST:event_studentOptionMouseExited

    private void lecturersOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturersOptionMouseEntered
        // TODO add your handling code here:
        setColor(lecturersOption);
    }//GEN-LAST:event_lecturersOptionMouseEntered

    private void lecturersOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturersOptionMouseExited
        // TODO add your handling code here:
        resetColor(lecturersOption);
    }//GEN-LAST:event_lecturersOptionMouseExited

    private void adminOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminOptionMouseEntered
        // TODO add your handling code here:
        setColor(adminOption);
    }//GEN-LAST:event_adminOptionMouseEntered

    private void adminOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminOptionMouseExited
        // TODO add your handling code here:
        resetColor(adminOption);
    }//GEN-LAST:event_adminOptionMouseExited

    private void loginOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginOptionMouseEntered
        // TODO add your handling code here:
        setColor(loginOption);
    }//GEN-LAST:event_loginOptionMouseEntered

    private void loginOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginOptionMouseExited
        // TODO add your handling code here:
        resetColor(loginOption);
    }//GEN-LAST:event_loginOptionMouseExited

    private void aboutOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutOptionMouseEntered
        // TODO add your handling code here:
        setColor(aboutOption);
    }//GEN-LAST:event_aboutOptionMouseEntered

    private void aboutOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutOptionMouseExited
        // TODO add your handling code here:
        resetColor(aboutOption);
    }//GEN-LAST:event_aboutOptionMouseExited

    private void studentOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentOptionMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new StudentData().show();
    }//GEN-LAST:event_studentOptionMousePressed

    private void lecturersOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturersOptionMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new LecturerData().show();
    }//GEN-LAST:event_lecturersOptionMousePressed

    private void loginOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginOptionMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            PrintWriter pw = new PrintWriter("loginsessions.txt");
            pw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        new Login().show();
    }//GEN-LAST:event_loginOptionMousePressed

    private void adminOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminOptionMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new Admin().show();
    }//GEN-LAST:event_adminOptionMousePressed

    private void aboutOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutOptionMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new About().show();
    }//GEN-LAST:event_aboutOptionMousePressed

    private void jLabel11ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel11ComponentShown
        // TODO add your handling code here:
        LoginSession newUser  = new LoginSession();
        if(newUser.getLoginState()){
            this.jLabel11.setText("Login");
        }
        else{
            this.jLabel11.setText("Logout");
        }
    }//GEN-LAST:event_jLabel11ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String email = "";
        String user = "";
        
        try {
            BufferedReader fileReader = new BufferedReader(new FileReader("loginsessions.txt"));
            String line = fileReader.readLine();
            while (line != null) {
                email = line.split(",")[0];
                user = line.split(",")[2];
                line = fileReader.readLine();
            }
            fileReader.close();
            this.jLabel11.setText("Logout");
            this.userId.setText(""+user+""+">"+""+email);
            
            if(user.equalsIgnoreCase("student")){
                this.lecturersOption.setVisible(false);
                this.adminOption.setVisible(false);
 
            }
            if(user.equalsIgnoreCase("lecturer")){
                this.adminOption.setVisible(false);
                this.studentOption.setVisible(false);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(197,197,197));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(java.awt.Color.GRAY);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutOption;
    private javax.swing.JPanel adminOption;
    private javax.swing.JPanel background;
    private javax.swing.JPanel homeOption;
    private javax.swing.JLabel homeTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lecturersOption;
    private javax.swing.JPanel loginOption;
    private javax.swing.JSeparator searchBottomBorder;
    private javax.swing.JTextArea searchInput;
    private javax.swing.JPanel studentOption;
    private javax.swing.JLabel systemTitle;
    private javax.swing.JLabel systemType;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel userId;
    // End of variables declaration//GEN-END:variables
}
